[project]
name = "demo-voice-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "aiohttp>=3.13.3",
    "fastapi>=0.134.0",
    "firebase-admin>=7.2.0",
    "livekit-agents[openai,silero,speechmatics]>=1.4,<1.5",
    "livekit-plugins-backboard",
    "numpy>=2.2,<2.3",
    "pipecat-ai-small-webrtc-prebuilt>=2.3.0",
    "pipecat-ai[silero,speechmatics,webrtc]>=0.0.103",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "sounddevice>=0.5.5",
    "uvicorn>=0.41.0",
    "websockets>=13",
]

[tool.uv.sources]
livekit-plugins-backboard = { path = "packages/livekit-plugins-backboard" }
